spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        enable.idempotence: true

producer:
  topic: ${PRODUCER_TOPIC:video-views-topic}
  count: ${PRODUCER_COUNT:1000000}
  sleep-ms: ${PRODUCER_SLEEP_MS:100}
  dry-run: ${PRODUCER_DRY_RUN:false}

logging:
  level:
    root: info
    com.hack.dataset: info
